SearchJobNet_project/Controllers/HistoryController/HistoryController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using HM = SearchJobNet_project.Models.HistoryModel;
using CM = SearchJobNet_project.Models.CommentModel;
using SJM = SearchJobNet_project.Models.SearchJobModel;


namespace SearchJobNet_project.Controllers.HistoryController
{
    public class HistoryController : Controller
    {
        // 建立建構子
        public HistoryController() { }

        //轉至歷史紀錄頁面
        public ActionResult Index()
        {
            // 搜尋職缺欄位內容種類
            SJM.SearchJob sjm = new SJM.SearchJob();
            ViewBag.WorkType = sjm.getWorkType();
            ViewBag.CityName = sjm.getCityName();
            ViewBag.Cjob_Name1 = sjm.getCjob_Name1();
            return View("HistoryView");
        }

        #region 歷史紀錄功能 [生成瀏覽紀錄/瀏覽瀏覽紀錄/瀏覽評論紀錄]

        // 傳入 歷史model, 執行[生成瀏覽職缺紀錄] 功能
        // 回傳 成功新增資料與否
        [HttpPost]
        public ActionResult insertHistory(int jobID)
        {
            string msg = "";
            HM.History hm = new HM.History();
            if (Session["suserID"] == null || string.IsNullOrWhiteSpace(Session["suserID"].ToString()))
            {
                System.Diagnostics.Debug.Print("還沒登入");
            }
            else
            {
                msg = hm.insertHistory(Session["suserID"].ToString(), jobID);
            }
            return Content(msg);
        }
        [HttpPost]
        // 傳入 使用者PK 執行 [瀏覽瀏覽職缺紀錄] 功能
        // 回傳 整筆資料或部分資料(json的HistoryModel型態)
        public ActionResult browseHistoryjob()
        {

            HM.History hm = new HM.History();
            List<HM.HistoryModel> hmModel = new List<HM.HistoryModel>();

            hmModel = hm.browseHistoryjob(Session["suserID"].ToString());




            return Json(hmModel);

        }


        // 傳入 使用者PK 執行 [瀏覽歷史評論紀錄] 功能
        // 回傳 整筆資料或部分資料(json的HistoryModel型態)
        public ActionResult browseHistoryComment()
        {
            System.Diagnostics.Debug.Print(Session["suserID"].ToString() + " this is");
            CM.Comment comment = new CM.Comment();
            List<CM.CommentModel> hcommentModel = new List<CM.CommentModel>();
            hcommentModel = comment.browseHistoryComment(Session["suserID"].ToString());
            
            return Json(hcommentModel);
        }


        #endregion
    }
}

SearchJobNet_project/Controllers/JobController/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SJM = SearchJobNet_project.Models.SearchJobModel;
using JM = SearchJobNet_project.Models.JobModel;
using Newtonsoft.Json;

namespace SearchJobNet_project.Controllers.JobController
{
    public class JobController : Controller
    {
        // 到JobList頁面
        // 傳入 搜尋職缺model,執行 [查看職缺清單] 功能
        // 回傳 職缺清單
        public ActionResult Index(SJM.SearchJobModel searchModel)
        {
            // 搜尋職缺欄位內容種類
            SJM.SearchJob sjm = new SJM.SearchJob();
            ViewBag.DWorkType = sjm.getWorkType();
            ViewBag.DCityName = sjm.getCityName();
            ViewBag.DCjob_Name1 = sjm.getCjob_Name1();

            ViewBag.CityName = searchModel.CityName;
            ViewBag.Wk_Type = searchModel.Wk_Type;
            ViewBag.CompName = searchModel.CompName;
            ViewBag.Cjob_Name1 = searchModel.Cjob_Name1;

            ViewBag.SearchJobCol = searchModel;

            return View("JobListView");
        }
        [HttpPost()]
        public ActionResult SendJobListData(SJM.SearchJobModel searchModel)
        {
            SJM.SearchJob sjm = new SJM.SearchJob();
            List<SJM.SearchJobModel> sjModel = new List<SJM.SearchJobModel>();
            sjModel = sjm.jobList(searchModel);

            return this.Json(sjModel);
        }

        //到職缺細項頁面
        // 傳入 職缺PK,執行 [查看職缺細項] 功能
        // 回傳 整筆資料或部分資料(list的JobModel型態)

            //for test 12/16

        //public ActionResult toJobDetailView(string jobID)
        public ActionResult toJobDetailView(int jobID)
        {
            SJM.SearchJob sjm = new SJM.SearchJob();
            JM.JobModel jmModel = new JM.JobModel();
            string userID = "";
            if (Session["suserID"]!=null) {
                 userID = Session["suserID"].ToString();
            }
            jmModel = sjm.jobDetail(jobID, userID);
            //jmModel = sjm.jobDetail(1);

            // 搜尋職缺欄位內容種類
            ViewBag.DWorkType = sjm.getWorkType();
            ViewBag.DCityName = sjm.getCityName();
            ViewBag.DCjob_Name1 = sjm.getCjob_Name1();

            return View("JobDetailView", jmModel);
        }

        //到我的最愛頁面

        public ActionResult toMyFavoriteView()
        {
            SJM.SearchJob sjm = new SJM.SearchJob();
            ViewBag.DWorkType = sjm.getWorkType();
            ViewBag.DCityName = sjm.getCityName();
            ViewBag.DCjob_Name1 = sjm.getCjob_Name1();
            return View("MyFavoriteView");
        }

        [HttpPost()]
        public ActionResult memberToMyFavoriteView()
        {
            SJM.SearchJob sjm = new SJM.SearchJob();
            List<SJM.SearchJobModel> sjModel = new List<SJM.SearchJobModel>();
            string userID = Session["suserID"].ToString();
            sjModel = sjm.myFavorite(userID);
            
            return this.Json(sjModel);
            //return View("MyFavoriteView");
        }

        // 傳入 使用者ID與職缺ID,執行 [加到我的最愛] 功能
        // 回傳 成功新增資料與否
        [HttpPost]
        public ActionResult insertMyFavorite(string user_ID , int job_ID)
        {
            string msg = "";
            SJM.SearchJob sjm = new SJM.SearchJob();
            msg = sjm.insertMyFavorite(user_ID, job_ID);
            return Content(msg);
        }

        // 傳入 使用者ID與職缺ID [刪除我的最愛] 功能
        // 回傳 成功修改資料與否
        [HttpPost]
        public ActionResult deleteMyFavorite(string user_ID, int job_ID)
        {
            string msg = "";
            SJM.SearchJob sjm = new SJM.SearchJob();
            msg = sjm.delMyFavorite(user_ID, job_ID);
            return Content(msg);
        }
    }
}

SearchJobNet_project/Views/Job/MyFavoriteView.cshtml
@{
    Layout = null;
    var suserID = "";                                                                                   //判斷是否登入 不然跳轉回主頁
    var suserName = "";
    if (Session["suserID"] == null || string.IsNullOrWhiteSpace(Session["suserID"].ToString()))
    {
        <script>alert("請先登入");</script>
        Response.Write("<script>alert('請先登入!!'); location.href='/'; </script>");    //實現登入後alert然後跳轉
    }
    else
    {
        suserName=Session["suserName"].ToString();
        suserID = Session["suserID"].ToString();
    }
}

<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>MyFavorite</title>
    <!--/metadata -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta name="keywords" content="" />
    <script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
    </script>
    <!-- //for-mobile-apps -->
    <link href="~/browser_components/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/browser_components/css/font-awesome.css" rel="stylesheet" type="text/css" media="all" />
    <!-- header and footer stylesheet -->
    <link href="~/browser_components/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //header and footer stylesheet -->
    <!-- lightbox css file -->
    <link href="~/browser_components/css/lightcase.css" rel="stylesheet" type="text/css" />
    <!-- css file -->
    <!-- Testimonials-slider-css-files -->
    <link href="~/browser_components/css/owl.theme.css" rel="stylesheet">
    <!-- //Testimonials-slider-css-files -->
    <!-- online fonts -->
    <link href="http://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- //online fonts -->
    <link href="~/Content/kendo/kendo.default.min.css" rel="stylesheet" />
    <link href="~/Content/kendo/kendo.common.min.css" rel="stylesheet" />
    <!-- js -->
    <script src="~/browser_components/js/jquery-2.2.3.min.js"></script>
    <!-- //js-->
    <script src="~/scripts/kendo/kendo.all.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/scripts/MyFavorite.js"></script>
    <link href="~/scripts/Shared.css" rel="stylesheet" />
</head>

<body>
    <!-- banner -->
    <div class="banner jarallax">
        <div class="w3layouts-header-top"  style="padding-top: 5px;padding-bottom: 5px;">
            <div class="container">
                <div class="w3-header-top-grids">
                    <div class="w3-header-top-left">
                    </div>
                    <div class="w3-header-top-right">
                        <div class="agileinfo-social-grids">
                            <div id="loginName">
                                <h3 style="font-family:Microsoft JhengHei;color:white">
                                    @suserName
                                <button id="exitimg" style="background-color:transparent;border-color:transparent">
                                    <img src="~/browser_components/images/exit.png" width="40" height="40" />
                                </button>
                            </h3>

                        </div>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <div class="head">
            <div class="container">
                <div class="navbar-top">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="navbar-brand logo ">
                            <h1 style="font-family:Microsoft JhengHei;"> @Html.ActionLink("求職網", "Index", "Home")</h1>
                        </div>

                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav link-effect-4" style="font-size:large">
                            <li class="active first-list">@Html.ActionLink("回首頁", "Index", "Home") </li>
                            <li><a href="#" data-toggle="modal" data-target="#searchjob">職缺查詢</a> </li>
                            <li>@Html.ActionLink("我的最愛", "toMyFavoriteView", "Job") </li>
                            <li>@Html.ActionLink("歷史紀錄", "Index", "History")</li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div>
            </div>
        </div>
        <div class="w3layouts-banner-slider">
            <div class="container">
                <div class="slider">
                    <div class="callbacks_container">
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
    </div>
    <!-- //banner -->
    <!-- banner-bottom -->
    <div id="about" class="banner-bottom">
        <div class="container">
            <div class="wls_head_all">
                <h3 style="font-family:Microsoft JhengHei;">我的最愛</h3>
            </div>
            <!--產生我的最愛表單-->
            <div id="grid"></div>
                <div class="clearfix"> </div>
        </div>
    </div>
    <!-- //banner-bottom -->
    <!-- footer -->
    <footer>
        <div class="agileits-w3layouts-footer">
            <div class="container">
                <div class="col-md-12 w3-agile-grid">
                    <h5>About Us</h5>
                    <p style="text-align:center;font-family: 'Microsoft JhengHei';">中央大學資訊管理研究所碩士一年級<br />陳芃諭 王美淋 鍾文翔 劉冠慶 蔡沅廷</p>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <p>第八組</p>
            </div>
        </div>
    </footer>
    <!-- //footer -->
    <!-- bootstrap-modal-pop-up -->
    <div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    Interior Show
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <img src="~/browser_components/images/modal1.jpg" alt=" " class="img-responsive" />
                    <p>
                        Ut enim ad minima veniam, quis nostrum
                        exercitationem ullam corporis suscipit laboriosam,
                        nisi ut aliquid ex ea commodi consequatur? Quis autem
                        vel eum iure reprehenderit qui in ea voluptate velit
                        esse quam nihil molestiae consequatur, vel illum qui
                        dolorem eum fugiat quo voluptas nulla pariatur.
                        <i>
                            " Quis autem vel eum iure reprehenderit qui in ea voluptate velit
                            esse quam nihil molestiae consequatur.
                        </i>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- //bootstrap-modal-pop-up -->

    <!--搜尋職缺popup-->
    <!-- bootstrap-modal-pop-up -->
    <div class="modal video-modal fade" id="searchjob" tabindex="-1" role="dialog" aria-labelledby="searchjob">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    搜尋職缺
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>

                <div class="modal-body">
                    <img src="~/browser_components/images/modal1.jpg" alt=" " class="img-responsive" />

                    <ul class="fields" vailgn="center">

                        <li class="first-list">
                            <div class="fields-label" style="margin-top:20px;margin-left:180px;">
                                @Html.Label("公司名稱：", new { style = "width: 80px;" })
                                <input id="DCompName" class="k-textbox k-input" style="width:160px;" />
                            </div>
                            <div class="fields-value" style="margin-top:20px;margin-left:180px">
                                @Html.Label("工作性質：", new { style = "width: 80px;" })
                                @Html.DropDownList("工作性質", (IEnumerable<SelectListItem>)ViewBag.DWorkType, "不拘", new { @class = "k-textbox k-input", style = "width:160px;", id = "DWorkType" })

                            </div>
                            <div class="fields-value" style="margin-top:20px;margin-left:180px">
                                @Html.Label("工作地點：", new { style = "width: 80px;" })
                                @Html.DropDownList("工作地點", (IEnumerable<SelectListItem>)ViewBag.DCityName, "不拘", new { @class = "k-textbox k-input", style = "width:160px;", id = "DCityName" })

                            </div>
                            <div class="fields-value" style="margin-top:20px;margin-left:180px">
                                @Html.Label("職務類別：", new { style = "width: 80px;" })
                                @Html.DropDownList("請選擇職務類別", (IEnumerable<SelectListItem>)ViewBag.DCjob_Name1, "不拘", new { @class = "k-textbox k-input", style = "width:160px;", id = "DCjob_Name1" })

                            </div>
                        </li>

                    </ul>
                    <div class="form-footer" style="text-align:right;margin-right:30px;margin-bottom:20px">
                        <button type="submit" class="btn btn-primary" id="searchJobButton">搜尋</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- //bootstrap-modal-pop-up -->
    <!-- banner-responsive-slider -->
    <script src="~/browser_components/js/responsiveslides.min.js"></script>
    <script>
		// You can also use "$(window).load(function() {"
		$(function () {
			// Slideshow 4
			$("#slider4").responsiveSlides({
				auto: true,
				pager: true,
				nav: false,
				speed: 500,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});

		});
    </script>
    <!-- //banner-responsive-slider -->
    <!-- light-case -->
    <script src="~/browser_components/js/lightcase.js"></script>
    <script>
		$('.showcase').lightcase();
    </script>
    <!-- //light-case -->
    <!-- for testimonials slider-js-file-->
    <script src="~/browser_components/js/owl.carousel.js"></script>
    <!-- //for testimonials slider-js-file-->
    <script>
		$(document).ready(function() {
		$("#owl-demo").owlCarousel({

			autoPlay: 3000, //Set AutoPlay to 3 seconds
			autoPlay:true,
			items : 3,
			itemsDesktop : [640,5],
			itemsDesktopSmall : [414,4]
		});
		$("#home").click(function () {
		    window.location = "\\Home";
		});
		});
    </script>
    <!-- for testimonials slider-js-script-->
    <!-- smooth-scrolling -->
    <script src="~/browser_components/js/move-top.js"></script>
    <script src="~/browser_components/js/easing.js"></script>
    <script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();

				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
    </script>
    <script src="~/browser_components/js/SmoothScroll.min.js"></script>
    <!-- //smooth-scrolling -->
    <script>
		$(document).ready(function () {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
    </script>
    <!-- smooth-scrolling-of-move-up -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/browser_components/js/bootstrap.js"></script>
</body>

</html>